# Generated by Django 4.2.6 on 2023-10-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0002_remove_question_question_text_question_bug_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('bug_type', models.CharField(choices=[('ERROR', 'Error'), ('NEW FEATURE', 'New Feature'), ('INTEGRATION', 'Integration'), ('OTHER', 'Other')], max_length=200)),
                ('report_date', models.DateTimeField(verbose_name='Date Reported')),
                ('status', models.CharField(choices=[('TO DO', 'To Do'), ('IN PROGRESS', 'In Progress'), ('DONE', 'Done')], max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
